ProductBacklog.Web/Models/ErrorViewModel.cs
using System;

namespace ProductBacklog.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProductBacklog.Web/Models/EstadoEnum.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProductBacklog.Web.Models
{
    public enum EstadoEnum
    {
        activo = 0,
        inactivo = 1,
        Pendiente = 2,
        Atrasado = 3
    }
}

ProductBacklog.Web/Models/HistoriaUsuario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProductBacklog.Web.Models
{
    public class HistoriaUsuario : ModelBase
    {
        public string Descripcion { get; set; }

        public string Observacion { get; set; }

        public EstadoEnum Estado { get; set; }

        public HistoriaUsuario(string descripcion, string observacion, EstadoEnum estado):base()
        {
            if (string.IsNullOrWhiteSpace(descripcion))
            {
                throw new ArgumentNullException("es necesario la descripcion para crear la HU");
            }
            else if (string.IsNullOrWhiteSpace(observacion))
            {
                throw new ArgumentNullException("es necesario crear la observacion para HU");
            }
            else
            {
                this.Descripcion = descripcion;
                this.Estado = estado;
                this.Observacion = observacion;
            }
        }

        public HistoriaUsuario()
        {

        }
    }
}

ProductBacklog.Web/Models/ModelBase.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProductBacklog.Web.Models
{
    public abstract class ModelBase
    {
        public string Id { get; set; }

        public ModelBase()
        {
            this.Id = Guid.NewGuid().ToString();
        }
    }
}

ProductBacklog.Web/Controllers/HistoriaUsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProductBacklog.Web.Data;
using ProductBacklog.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProductBacklog.Web.Controllers
{
    public class HistoriaUsuarioController : Controller
    {
        private readonly ProductBackLogContext productBackLogContext;

        public HistoriaUsuarioController(ProductBackLogContext productBackLogContext)
        {
            this.productBackLogContext = productBackLogContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            //obtenermos el listado de historias 
            List<HistoriaUsuario> historias = await this.productBackLogContext.HistoriasUsuarios.ToListAsync();

            //retornar el listado de h
            return View(historias);
        }

        [HttpGet]
        public IActionResult Guardar()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Guardar([Bind()]HistoriaUsuario historiaUsuario)
        {
            //adicionar en la db el hu
            await productBackLogContext.HistoriasUsuarios.AddAsync(historiaUsuario);
            await productBackLogContext.SaveChangesAsync();

            //redirecionamos el index
            return RedirectToAction("Index");
        }
    }
}

ProductBacklog.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProductBacklog.Web.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ProductBacklog.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProductBacklog.Web/Views/HistoriaUsuario/Guardar.cshtml
@using ProductBacklog.Web.Models
@model HistoriaUsuario
@{
    ViewData["Title"] = "Guardar";
}

<h1>Guardar</h1>

<form method="post">
    <div class="form-group">
        <label asp-for="@Model.Descripcion" class="control-label"></label>
        <input asp-for="@Model.Descripcion" type="text" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="@Model.Observacion" class="control-label"></label>
        <input asp-for="@Model.Observacion" type="text" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="@Model.Estado" class="control-label"></label>
        <input asp-for="@Model.Estado" type="number" class="form-control" />
    </div>

    <div class="col-sm">
        <input asp-controller="HistoriaUsuario" asp-action="Guardar" type="submit" value="guardar" class="btn btn-outline-dark" />
    </div>
</form>

ProductBacklog.Web/Views/HistoriaUsuario/Index.cshtml
@using ProductBacklog.Web.Models
@model List<HistoriaUsuario>
@{
    ViewData["Title"] = "Index";
}

<h1>..... </h1>

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Id</th>
            <th scope="col">Observacion</th>
            <th scope="col">Descriccio</th>
            <th scope="col">estado</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var historia in Model)
        {
        <tr>
            <th scope="row">1</th>
            <td>@historia.Id</td>
            <td>@historia.Observacion</td>
            <td>@historia.Descripcion</td>
            <td>@historia.Estado</td>
        </tr>
        }
    </tbody>
</table>

ProductBacklog.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>bienbenido a flilp</p>
</div>

ProductBacklog.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProductBacklog.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProductBacklog.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HistoriaUsuario" asp-action="Index">Mostrar Backlog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="HistoriaUsuario" asp-action="Guardar">Adicionarle backlog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ProductBacklog.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>